version: '3'

services:
  # Database
  db:
    image: mysql:8.0  # Utilisez la version appropriée pour x86_64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hidopi2023
      MYSQL_DATABASE: mycra-hidopi
      MYSQL_USER: mycra-hidopi
      MYSQL_PASSWORD: Hidopi2023
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.1  # Utilisez la version appropriée pour x86_64
    restart: always
    ports:
      - '8001:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Hidopi2023
    networks:
      - wpsite

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:5.8  # Utilisez la version appropriée pour x86_64
    ports:
      - '8000:80'
      - '443:443'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mycra-hidopi
      WORDPRESS_DB_PASSWORD: Hidopi2023
    networks:
      - wpsite

networks:
  wpsite:
    driver: bridge

volumes:
  db_data:
