version: '3'

services:
  # Database
  db:
    image: arm64v8/mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nassira14
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Nassira14
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: arm64v8/phpmyadmin:5.1
    restart: always
    ports:
      - '8001:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Nassira14
    networks:
      - wpsite

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: arm64v8/wordpress:5.8
    ports:
      - '8000:80'
      - '443:443'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Nassira14
    networks:
      - wpsite

networks:
  wpsite:
    driver: bridge

volumes:
  db_data:
