version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwordvart
      MYSQL_DATABASE: vartbd
      MYSQL_USER: vartsite
      MYSQL_PASSWORD: passwordvart
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9001:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passwordvart 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '9000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: vartsite
      WORDPRESS_DB_PASSWORD: passwordvart
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: